Refactor: Numbered section
cal-itp/calitp.org pull request #136
Opened 2023-05-17 21:37 UTC by machikoyasuda

closes #101 

Thanks to https://stackoverflow.com/questions/5732836/html-css-numbered-list-with-numbers-inside-of-circles

- [x] refactor picture/image HTML with `<ul>` `<ol>` and CSS pseudoelement circles
- [x] delete unused images
- [x] delete unused css
- [x] update copy
- [x] update image border
- [x] use correct colors

<img width="1512" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/fc8f63e0-e0ed-406f-886d-99365f4d5021">
<img width="1512" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/2fcf4b4d-5797-4d2c-9131-a3babc02a289">

2023-05-17 22:01 UTC, machikoyasuda commented
This is now ready for review @angela-tran @thekaveman

2023-05-17 22:15 UTC, thekaveman commented
Wait I thought `.constricted` was removed in #133 but it is back here?

2023-05-17 22:17 UTC, machikoyasuda commented
@thekaveman Oh my bad. Painful rebase.

2023-05-17 22:18 UTC, thekaveman requested changes

2023-05-17 22:18 UTC, thekaveman commented on src/index.html
> +
Looks like some extra whitespace got in here

2023-05-17 22:18 UTC, thekaveman commented on src/index.html
> +
Whitespace

2023-05-17 22:18 UTC, thekaveman commented on src/index.html
> +
Whitespace

2023-05-17 22:18 UTC, thekaveman commented on src/index.html
> +
Whitespace

2023-05-17 22:36 UTC, thekaveman commented
@mrose914 can you please review the content of this numbered section: https://deploy-preview-136--cal-itp-website.netlify.app/

We used the exact wording from the content doc, just want to make sure this is the intended casing:

<img width="551" alt="image" src="https://github.com/cal-itp/calitp.org/assets/1783439/11ed46dd-d68d-4040-a6db-8a2e695c3879">

2023-05-18 16:14 UTC, machikoyasuda commented
@thekaveman Could we still merge this w/o waiting on final copy? I can make a new Issue for the copy issue on just the numbered area. This PR moves the giant <section>s around and it's going to be helpful for subsequent PRs (or an enormous rebase headache).

2023-05-18 16:26 UTC, thekaveman approved these changes

2023-05-18 16:28 UTC, merged