feat: create issue form for Press items
cal-itp/calitp.org pull request #205
Opened 2023-06-15 22:19 UTC by machikoyasuda

closes #187

2023-06-16 17:33 UTC, machikoyasuda commented on .github/ISSUE_TEMPLATE/new_press.yml
> +labels: press
```suggestion
labels:
  - content
  - press
```

2023-07-03 16:46 UTC, thekaveman requested changes

2023-07-03 16:46 UTC, thekaveman commented on .github/ISSUE_TEMPLATE/new_press.yml
> +      description: The date is used for press releases. Not required for external press links.
We need the date even for external press releases, it shows up on the listing page.

2023-07-03 16:46 UTC, thekaveman commented on .github/ISSUE_TEMPLATE/new_press.yml
> +      description: The date is used for press releases. Not required for external press links.
We need the date even for external press releases, it shows up on the listing page.

2023-07-03 16:46 UTC, thekaveman commented on .github/ISSUE_TEMPLATE/new_press.yml
> +      description: The date is used for press releases. Not required for external press links.
Since there is a separate Year and Month field, I think this is duplicative right?

2023-07-05 17:01 UTC, machikoyasuda commented
Tested out the new issue template here:

<img width="1512" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/3f356a8a-f04c-435e-91bf-4b426fcb4343">
<img width="1512" alt="image" src="https://github.com/cal-itp/calitp.org/assets/3673236/3087cf5c-74fc-4eff-8685-849e955f51e1">

Form: https://github.com/machikoyasuda/kindara-client-gem/issues/new?assignees=&labels=content%2Cpress&projects=&template=new_press.yml&title=New+press+request

Created this issue: https://github.com/machikoyasuda/kindara-client-gem/issues/8 (The labels aren't on there b/c this repository doesn't have those labels).

2023-07-06 15:45 UTC, thekaveman commented on .github/ISSUE_TEMPLATE/new_press.yml
> +      required: true
```suggestion
```

We can make `location` optional since we have a default value

2023-07-06 20:08 UTC, thekaveman approved these changes

2023-07-06 23:36 UTC, merged